/*------------------------------------------------------------------------------
--                                                                            --
--       This software is confidential and proprietary and may be used        --
--        only as expressly authorized by a licensing agreement from          --
--                                                                            --
--                            Verisilicon.                                    --
--                                                                            --
--      In the event of publication, the following notice is applicable:      --
--                                                                            --
--                   (C) COPYRIGHT 2020 HANTRO PRODUCTS OY                    --
--                            ALL RIGHTS RESERVED                             --
--                                                                            --
--         The entire notice above must be reproduced on all copies.          --
--                                                                            --
--------------------------------------------------------------------------------
--
--  Abstract : EWL Hardware Config for different target.
--
------------------------------------------------------------------------------*/

{
  .hw_build_id = 0x7000217e,
  .hw_asic_id = 0x90004200,
  .hevcEnabled = 1,
  .h264Enabled = 1,
  .jpegEnabled = 1,
  .vp9Enabled = 0,
  .av1Enabled = 0,
  .cuTreeSupport = 0,
  .maxEncodedWidthHEVC = 8192,
  .maxEncodedWidthH264 = 8192,
  .maxEncodedWidthAV1 = 0,
  .maxEncodedWidthVP9 = 0,
  .videoHeightExt = 0,
  .maxEncodedWidthJPEG = 32768,
  .bFrameEnabled = 0,
  .main10Enabled = 1,
  .RDOQSupportH264 = 0,
  .RDOQSupportHEVC = 0,
  .RDOQSupportAV1 = 0,
  .RDOQSupportVP9 = 0,
  .meHorSearchRange = 2,
  .meVertSearchRangeH264 = 6,
  .meVertSearchRangeHEVC = 8,
  .meVSRUnitSize = 8,
  .ssimSupport = 0,
  .psnrSupport = 0,
  .ssimSupportAV1 = 0,
  .psnrSupportAV1 = 0,
  .hevcTileSupport = 0,
  .saoSupport = 1,
  .rfcEnable = 1,
  .RFCVersion = 0,
  .roiBlkSize = 0,
  .roiMapVersion = 2,
  .cuInforVersion = 0,
  .cuInfoNoMean = 0,
  .ctbRcSupport = 1,
  .ctbRcVersion = 1,
  .frameInfoSupport = 0,
  .progRdoEnable = 1,
  .ljpegSupport = 0,
  .JpegRoiMapSupport = 0,
  .jpeg400Support = 1,
  .jpeg422Support = 1,
  .JpegDHTGenerate = 0,
  .JpegExternalDHT = 0,
  .meVertRangeProgramable = 1,
  .MonoChromeSupport = 1,
  .HevcYUV422Support = 0,
  .H264YUV422Support = 0,
  .HevcYUV444Support = 0,
  .H264YUV444Support = 0,
  .HevcTransSkipSupport = 1,
  .intraTU32Enable = 1,
  .bMultiPassSupport = 0,
  .tu32Enable = 1,
  .dynamicMaxTuSize = 1,
  .CtbBitsOutSupport = 0,
  .encVisualTuneSupport = 0,
  .ctbRcMoreMode = 1,
  .deNoiseEnabled = 0,
  .encRef4NInputSupport = 1,
  .encPsyTuneSupport = 0,
  .motionScoreEnable = 0,
  .reconSSEsupport = 0,
  .maxRefNumList0Minus1 = 0,
  .encSliceSizeBits = 10,
  .asymPuSupport = 1,
  .maxMergeCand4Support = 0,
  .enMe4nSearch = 1,
  .searchMe1n3Win = 0,
  .encAQInfoOut = 0,
  .prpVersion = 1,
  .rgbEnabled = 1,
  .NonRotationSupport = 0,
  .NVFormatOnlySupport = 0,
  .prpLowLatencySupport = 0,
  .prpLowlatencySignalbyDDR = 0,
  .inLoopDSBilinearSupport = 0,
  .inLoopDSRatio = 0,
  .cscExtendSupport = 1,
  .scalingEnabled = 0,
  .scaled420Support = 0,
  .vsSupport = 0,
  .OSDSupport = 0,
  .maxOsdNum = 0,
  .MosaicSupport = 0,
  .maxMosaicNum = 0,
  .mosaicVersion = 0,
  .osdBlendVersion = 0,
  .OSDMapSupport = 0,
  .OSDMapVersion = 0,
  .tile8x8FormatSupport = 1,
  .tile4x4FormatSupport = 1,
  .customTileFormatSupport = 0,
  .rgb24bitFormatSupport = 1,
  .prpSbiSupport = 0,
  .ufbcSupport = 0,
  .superTileXSupport = 1,
  .tile64x4_8bFormatSupport = 0,
  .tile32x4_10bFormatSupport = 0,
  .prpAnalyzerSupport = 0,
  .prpMirrorSupport = 0,
  .VideoPX = 5,
  .meExternSramSupport = 0,
  .busWidth = 2,
  .busType = 0,
  .maxAXIAlignment = 0,
  .axi_burst_align_wr_common = 0,
  .axi_burst_align_wr_stream = 0,
  .axi_burst_align_wr_chroma_ref = 0,
  .axi_burst_align_wr_luma_ref = 6,
  .axi_burst_align_rd_common = 0,
  .axi_burst_align_rd_prp = 0,
  .axi_burst_align_rd_ch_ref_prefetch = 6,
  .axi_burst_align_rd_lu_ref_prefetch = 0,
  .axi_burst_align_wr_cuinfo = 0,
  .axi_burst_align_wr_4n_recon = 0,
  .axi_burst_align_rd_4n_ref = 0,
  .SaoBufOptSupport = 0,
  .lowLatClkGate = 0,
  .h264NalRefIdc2bit = 1,
  .av1ExtensionFlag = 0,
  .av1CarryOpt = 0,
  .roiAbsQpSupport = 1,
  .ROI8Support = 1,
  .h264CavlcEnable = 1,
  .refRingBufEnable = 1,
  .disableRecWtSupport = 1,
  .forceIntraCuSizeOpt = 0,
  .ME1NUseSad = 0,
  .IMSUseSatd4 = 0,
  .MEMDPkOrder = 0,
  .backgroundDetSupport = 0,
  .P010RefSupport = 0,
  .streamBufferChain = 0,
  .gmvSupport = 0,
  .IPCM8Support = 0,
  .av1InterpFilterSwitchable = 0,
  .IframeOnly = 0,
  .dynamicRdoSupport = 0,
  .tuneToolsSet2Support = 0,
  .hevcTemporalMvpSupport = 0,
  .av1TemporalMvpSupport = 0,
  .tmvpMcSupport = 0,
  .intraReconSupport = 0,
  .av1IntraReconSupport = 0,
  .hevcIntraTrDepth0 = 0,
  .chDistWeightSupport = 0,
  .h264RdoCoeffSimpleBinEst = 0,
  .realTu32Support = 0,
  .hevcCuRdoSupport = 0,
  .av1CuRdoSupport = 0,
  .meqnSimpleBinCost = 1,
  .meqnClipYBits = 0,
  .h264MeqnHevcIntp = 0,
  .streamMultiSegment = 0,
  .modSubjPrefer = 0,
  .twoRefPTMVPSupport = 0,
  .mexnBinCostRefine = 0,
  .ipdMpmUseTop = 0,
},
