#------------------------------------------------------------------------------
#-                                                                            --
#-       This software is confidential and proprietary and may be used        --
#-        only as expressly authorized by a licensing agreement from          --
#-                                                                            --
#-                            VeriSilicon Inc.                                --
#-                                                                            --
#-                   (C) COPYRIGHT 2015 VeriSilicon Inc                       --
#-                            ALL RIGHTS RESERVED                             --
#-                                                                            --
#-                 The entire notice above must be reproduced                 --
#-                  on all copies and should not be removed.                  --
#-                                                                            --
#------------------------------------------------------------------------------/

# list of used sourcefiles
AVS2_SRCS += software/source/avs2/avs2decapi.c \
             software/source/avs2/avs2_decoder.c \
             software/source/avs2/avs2_storage.c \
             software/source/avs2/avs2_dpb.c \
             software/source/avs2/avs2_fb_mngr.c \
             software/source/avs2/avs2_params.c \
             software/source/avs2/wquant.c \
             software/source/avs2/avs2_vlc.c \
             software/source/avs2/avs2hwd_api.c \
             software/source/avs2/avs2hwd_asic.c
