/*------------------------------------------------------------------------------
--                                                                            --
--       This software is confidential and proprietary and may be used        --
--        only as expressly authorized by a licensing agreement from          --
--                                                                            --
--                            VeriSilicon Inc.                                --
--                                                                            --
--                   (C) COPYRIGHT 2015 VeriSilicon Inc                       --
--                            ALL RIGHTS RESERVED                             --
--                                                                            --
--                 The entire notice above must be reproduced                 --
--                  on all copies and should not be removed.                  --
--                                                                            --
--
--  Abstract : Hantro H1 JPEG Encoder API
--
------------------------------------------------------------------------------*/

/*------------------------------------------------------------------------------

    Table of contents

    1. Include headers
    2. Module defines
    3. Data types
    4. Function prototypes

------------------------------------------------------------------------------*/

#ifndef __JPEGENCAPI_H__
#define __JPEGENCAPI_H__

#ifdef __cplusplus
extern "C" {
#endif

#include "base_type.h"
#include "enccommon.h"

/*------------------------------------------------------------------------------
    2. Module defines
------------------------------------------------------------------------------*/
/**
 * \defgroup jpegenc_api JPEG Encoder API
 * This section describes the APIs for the initialization and configuration of the JPEG encoder.
 * @{
 */

/** define the mimimum size of the buffer which is used to store JPEG headers generated by software */
#define JPEGENC_STREAM_MIN_BUF0_SIZE 1024

/** \brief JPEG encoder instance. */
typedef const void *JpegEncInst;

/** \brief The size of DEC400 Tile Status Header Data if existing. */
#define DEC400_HEADER_BUF_SIZE (128)

/** Function return values. */
typedef enum {
  JPEGENC_FRAME_READY = 1,             /**< \brief  Frame ready                 */
  JPEGENC_RESTART_INTERVAL = 2,        /**< \brief  Restart interval ready      */
  JPEGENC_OK = 0,                      /**< \brief  Operation succeeds          */
  JPEGENC_ERROR = -1,                  /**< \brief  Error                       */
  JPEGENC_NULL_ARGUMENT = -2,          /**< \brief  Null argument               */
  JPEGENC_INVALID_ARGUMENT = -3,       /**< \brief  Invalid argument            */
  JPEGENC_MEMORY_ERROR = -4,           /**< \brief  Memory error                */
  JPEGENC_INVALID_STATUS = -5,         /**< \brief  Invalid status              */
  JPEGENC_OUTPUT_BUFFER_OVERFLOW = -6, /**< \brief  Output buffer overflow      */
  JPEGENC_EWL_ERROR = -7,              /**< \brief  EWL error                   */
  JPEGENC_EWL_MEMORY_ERROR = -8,       /**< \brief  EWL memory error            */
  JPEGENC_HW_BUS_ERROR = -9,           /**< \brief  Hardware bus error          */
  JPEGENC_HW_DATA_ERROR = -10,         /**< \brief  Hardware data error         */
  JPEGENC_HW_TIMEOUT = -11,            /**< \brief  Hardware timeout            */
  JPEGENC_HW_RESERVED = -12,           /**< \brief  Reserved for hardware       */
  JPEGENC_SYSTEM_ERROR = -13,          /**< \brief  System error                */
  JPEGENC_INSTANCE_ERROR = -14,        /**< \brief  Invalid instance            */
  JPEGENC_HW_RESET = -15,              /**< \brief  Hardware reset              */
  JPEGENC_HW_SLICEINFO_TIMEOUT = -16,  /**< \brief  sliceinfo poll timeout      */
  JPEGENC_HW_UFBC_ERROR = -17          /**< \brief  ufbc error                  */
} JpegEncRet;

/** Picture frame type for initialization. */
typedef enum {
  JPEGENC_YUV420_PLANAR = ENC_PIXFMT_YUV420_PLANAR,       /**< \brief  YYYY... UUUU... VVVV...  */
  JPEGENC_YUV420_SEMIPLANAR = ENC_PIXFMT_YUV420_SEMIPLANAR,       /**< \brief  YYYY... UVUVUV...        */
  JPEGENC_YUV420_SEMIPLANAR_VU = ENC_PIXFMT_YUV420_SEMIPLANAR_VU,    /**< \brief  YYYY... VUVUVU...        */
  JPEGENC_YUV422_INTERLEAVED_YUYV = ENC_PIXFMT_YUV422_INTERLEAVED_YUYV, /**< \brief  YUYVYUYV...              */
  JPEGENC_YUV422_INTERLEAVED_UYVY = ENC_PIXFMT_YUV422_INTERLEAVED_UYVY, /**< \brief  UYVYUYVY...              */
  JPEGENC_RGB565 = ENC_PIXFMT_RGB565,                  /**< \brief  16-bit RGB 16bpp         */
  JPEGENC_BGR565 = ENC_PIXFMT_BGR565,                  /**< \brief  16-bit RGB 16bpp         */
  JPEGENC_RGB555 = ENC_PIXFMT_RGB555,                  /**< \brief  15-bit RGB 16bpp         */
  JPEGENC_BGR555 = ENC_PIXFMT_BGR555,                  /**< \brief  15-bit RGB 16bpp         */
  JPEGENC_RGB444 = ENC_PIXFMT_RGB444,                  /**< \brief  12-bit RGB 16bpp         */
  JPEGENC_BGR444 = ENC_PIXFMT_BGR444,                  /**< \brief  12-bit RGB 16bpp         */
  JPEGENC_RGB888 = ENC_PIXFMT_RGB888,                  /**< \brief  24-bit RGB 32bpp         */
  JPEGENC_BGR888 = ENC_PIXFMT_BGR888,                  /**< \brief  24-bit RGB 32bpp         */
  JPEGENC_RGB101010 = ENC_PIXFMT_RGB101010,               /**< \brief  30-bit RGB 32bpp         */
  JPEGENC_BGR101010 = ENC_PIXFMT_BGR101010,               /**< \brief  30-bit RGB 32bpp         */
  JPEGENC_YUV420_I010 = ENC_PIXFMT_YUV420_PLANAR_10BIT_I010,        /**< \brief  10-bit YUV 24bpp         */
  JPEGENC_YUV420_MS_P010 = ENC_PIXFMT_YUV420_PLANAR_10BIT_P010,     /**< \brief  10-bit YUVSP 24bpp       */
  JPEGENC_YUV420_PLANAR_10BIT_PACKED_PLANAR =
      ENC_PIXFMT_YUV420_PLANAR_10BIT_PACKED_PLANAR,     /**< \brief  10-bit YUV Planar Packed       */
  JPENC_YUV420_10BIT_PACKED_Y0L2 = ENC_PIXFMT_YUV420_10BIT_PACKED_Y0L2,  /**< \brief  YUY YVY Packed */
  JPEGENC_YUV420_PLANAR_8BIT_TILE_32_32 =
      ENC_PIXFMT_YUV420_PLANAR_8BIT_TILE_32_32, /**< \brief  8-bit 32x32 tile        */
  JPEGENC_YUV420_PLANAR_8BIT_TILE_16_16_PACKED_4 =
      ENC_PIXFMT_YUV420_PLANAR_8BIT_TILE_16_16_PACKED_4, /**< \brief  8-bit 16x16 tile packed 4  */
  JPEGENC_YUV420_SEMIPLANAR_8BIT_TILE_4_4 =
      ENC_PIXFMT_YUV420_SEMIPLANAR_8BIT_TILE_4_4, /**< \brief  YYYY... UVUVUV...        */
  JPEGENC_YUV420_SEMIPLANAR_VU_8BIT_TILE_4_4 =
      ENC_PIXFMT_YUV420_SEMIPLANAR_VU_8BIT_TILE_4_4, /**< \brief  YYYY... VUVUVU...        */
  JPEGENC_YUV420_PLANAR_10BIT_P010_TILE_4_4 =
      ENC_PIXFMT_YUV420_PLANAR_10BIT_P010_TILE_4_4,                                /**< \brief  YYYY... UVUV... */
  JPEGENC_YUV420_SEMIPLANAR_101010 = ENC_PIXFMT_YUV420_SEMIPLANAR_101010, /**< \brief  YYYY... UVUV... */
  JPEGENC_YUV422SP_888 = ENC_PIXFMT_YUV422_888, /**< \brief  YYYY... UVUVUV...        */
  JPEGENC_YUV420_UV_8BIT_TILE_128_2 = ENC_PIXFMT_YUV420_UV_8BIT_TILE_128_2, /**< \brief  YYYY... UVUV... */
  JPEGENC_YUV420_8BIT_TILE_8_8 = ENC_PIXFMT_YUV420_8BIT_TILE_8_8, /**< \brief  8-bit 8x8 tile              */
  JPEGENC_YUV420_10BIT_TILE_8_8 =
      ENC_PIXFMT_YUV420_10BIT_TILE_8_8,                     /**< \brief  10-bit 8x8 tile              */
  JPEGENC_YVU420_PLANAR = ENC_PIXFMT_YVU420_PLANAR, /**< \brief  10-bit 8x8 tile              */
  JPEGENC_YUV420_FBC64 = ENC_PIXFMT_YUV420_UV_8BIT_TILE_64_2,  /**< \brief  8-bit 64x2 tile          */
  JPEGENC_YUV420_UV_10BIT_TILE_128_2 =
      ENC_PIXFMT_YUV420_UV_10BIT_TILE_128_2,                    /**< \brief  10-bit 128x2 tile        */
  JPEGENC_RGB888_24BIT = ENC_PIXFMT_RGB888_24BIT, /**< \brief  24-bit RGB 24bpp (MSB) BGR (LSB) */
  JPEGENC_BGR888_24BIT = ENC_PIXFMT_BGR888_24BIT, /**< \brief  24-bit BGR 24bpp (MSB) RGB (LSB) */
  JPEGENC_RBG888_24BIT = ENC_PIXFMT_RBG888_24BIT, /**< \brief  24-bit RBG 24bpp (MSB) GBR (LSB) */
  JPEGENC_GBR888_24BIT = ENC_PIXFMT_GBR888_24BIT, /**< \brief  24-bit GBR 24bpp (MSB) RBG (LSB) */
  JPEGENC_BRG888_24BIT = ENC_PIXFMT_BRG888_24BIT, /**< \brief  24-bit BRG 24bpp (MSB) GRB (LSB) */
  JPEGENC_GRB888_24BIT = ENC_PIXFMT_GRB888_24BIT, /**< \brief  24-bit GRB 24bpp (MSB) BRG (LSB) */
   /** \brief YUV422 semi-planar, YYYY... VUVUVU... */
  JPEGENC_YVU422SP_888 = ENC_PIXFMT_YVU422SP_888,
  //JPEGENC_YUV422_888,                             /**< \brief   YYYY... UVUVUV...        */Todo: double check
  /** YYYY... UUUU... VVVV...  */
  //VCENC_YUV444_PLANAR = ENC_PIXFMT_YUV444_PLANAR, // 444 formats not merged
  /** X8Y8U8V8...*/
  //VCENC_YUV444_XYUV8888 = ENC_PIXFMT_YUV444_XYUV8888,
  /** X2Y10U10V10...*/
  //VCENC_YUV444_XYUV2101010 = ENC_PIXFMT_YUV444_XYUV2101010,
  /** 24-bit RGB 32bpp         */
  JPEGENC_RGBX8888 = ENC_PIXFMT_RGBX8888,
  /** 24-bit RGB 32bpp         */
  JPEGENC_BGRX8888 = ENC_PIXFMT_BGRX8888,
  /** 30-bit RGB 32bpp         */
  JPEGENC_RGBX1010102 = ENC_PIXFMT_RGBX1010102,
  /** 30-bit RGB 32bpp         */
  JPEGENC_BGRX1010102 = ENC_PIXFMT_BGRX1010102,
  /** YYYY... VUVUVU...  */
  JPEGENC_YVU420_PLANAR_10BIT_P010 = ENC_PIXFMT_YVU420_PLANAR_10BIT_P010,
  /** 8-bit YYYY... */
  JPEGENC_Y8b = ENC_PIXFMT_Y8b,
  /** 10-bit YYYY... */
  JPEGENC_Y10bWL = ENC_PIXFMT_Y10bWL,
  /** 10-bit YYYY... */
  JPEGENC_Y10bWH = ENC_PIXFMT_Y10bWH,
  /** 10-bit YUV420SP10b YYYY...UVUVUV... */
  JPEGENC_YUV420SP10b = ENC_PIXFMT_YUV420SP10b,
  JPEGENC_YUV422_INTERLEAVED_YVYU = ENC_PIXFMT_YUV422_INTERLEAVED_YVYU, /**< \brief  YVYUYVYU...              */
  JPEGENC_YUV422_INTERLEAVED_VYUY = ENC_PIXFMT_YUV422_INTERLEAVED_VYUY, /**< \brief  VYUYVYUY...              */
  JPEGENC_YVU420_8BIT_TILE_8_8 = ENC_PIXFMT_YVU420_8BIT_TILE_8_8,
  JPEGENC_YUV400_PLANAR_10BIT_PACKED =
      ENC_PIXFMT_YUV400_PLANAR_10BIT_PACKED,
  JPEGENC_FORMAT_MAX = ENC_PIXFMT_FORMAT_MAX
} JpegEncFrameType;

/** Specifies picture scan types for pre-processing.
 *
 * This enumeration is valid only if the value of <tt>EWLHwConfig_t.superTileXSupport</tt>
 *  is <tt>0</tt>. */
typedef enum {
  /** raster scan */
  JPEG_RASTER_SCAN = 0,
  /** supertileX scan */
  JPEG_SUPERTILEX_SCAN = 1
} JpegEncPictureScanType;

/** Specifies the mode of rotation for initialization. */
typedef enum {
  JPEGENC_ROTATE_0 = 0,
  JPEGENC_ROTATE_90R = 1, /**< 90-degree rotation clockwise. */
  JPEGENC_ROTATE_90L = 2, /**< 90-degree rotation counter-clockwise. */
  JPEGENC_ROTATE_180 = 3  /**< 180-degree rotation. */
} JpegEncPictureRotation;

/** Specifies the mode of RGB-to-YUV color space conversion. */
typedef enum {
  JPEGENC_RGBTOYUV_BT601 =
      0, /**< Conversion to YUV values without any range change according to Rec. ITU-R BT.601. */
  JPEGENC_RGBTOYUV_BT709 =
      1, /**< Conversion to YUV values without any range change according to Rec. ITU-R BT.709. */
  JPEGENC_RGBTOYUV_USER_DEFINED = 2, /**< User-defined color space conversion. */
  JPEGENC_RGBTOYUV_BT2020 = 3, /**< Conversion according to Rec. ITU-R BT.2020. */
  /** Conversion from full range RGB to limited range YUV according to Rec. ITU-R BT.601. */
   JPEGENC_RGBFULL_TO_YUVLIMIT_BT601 = 4,
  /** (obsolete) Same as JPEGENC_RGBFULL_TO_YUVLIMIT_BT601. */
  JPEGENC_RGBTOYUV_BT601_FULL_RANGE = JPEGENC_RGBFULL_TO_YUVLIMIT_BT601,
  /** (Just for test) Conversion from RGB in range of (0~219) to limited range YUV
   * according to Rec. ITU-R BT.601. */
  JPEGENC_RGBTOYUV_BT601_LIMITED_RANGE = 5,
  /**< Conversion from full range RGB to limited range YUV according to Rec. ITU-R BT.709. */
  JPEGENC_RGBFULL_TO_YUVLIMIT_BT709 = 6,
  /** (obsolete) Same as JPEGENC_RGBFULL_TO_YUVLIMIT_BT709. */
  JPEGENC_RGBTOYUV_BT709_FULL_RANGE = JPEGENC_RGBFULL_TO_YUVLIMIT_BT709,
} JpegEncColorConversionType;

/** Specifies the encoding type. */
typedef enum {
  /** The frame is stored as a whole in the linear memory. */
  JPEGENC_WHOLE_FRAME = 0,
  /** The frame is sliced according to restart intervals, each with an input address. */
  JPEGENC_SLICED_FRAME
} JpegEncCodingType;

/** Specifies the encoding mode. */
typedef enum {
  /** YUV 420 mode. */
  JPEGENC_420_MODE = 0,
  /** YUV 422 mode (pre-processing only supports input formats JPEGENC_YUV422SP_888
  * and JPEGENC_YVU422SP_888). */
  JPEGENC_422_MODE = 1,
  /** Monochrome mode. */
  JPEGENC_MONO_MODE = 2,
  JPEGENC_CNT_MODE
} JpegEncCodingMode;

/** Specifies the unit type of X-coordinate and Y-coordinate. */
typedef enum {
  JPEGENC_NO_UNITS = 0,      /**< No unit, X and Y specify the pixel aspect ratio. */
  JPEGENC_DOTS_PER_INCH = 1, /**< Dots per inch. */
  JPEGENC_DOTS_PER_CM = 2,   /**< Dots per centimetre. */
} JpegEncAppUnitsType;

/** Specifies the type of marker for tables DHT and DQT. */
typedef enum {
   /** Luma and chroma tables are written behind one marker. */
  JPEGENC_SINGLE_MARKER = 0,
  /** Luma and chroma tables are written behind one marker per component. */
  JPEGENC_MULTI_MARKER
} JpegEncTableMarkerType;

/** Specifies the encoding format of thumbnail. */
typedef enum {
  /** Thumbnail encoded using JPEG format. */
  JPEGENC_THUMB_JPEG = 0x10,
  /** Thumbnail stored using one byte per pixel. */
  JPEGENC_THUMB_PALETTE_RGB8 = 0x11,
  /** Thumbnail stored using three bytes per pixel. */
  JPEGENC_THUMB_RGB24 = 0x13
} JpegEncThumbFormat;

/** Specifies the RC mode. */
typedef enum {
  JPEGENC_SINGLEFRAME = 0, /**< (Obsolete) Single frame mode. */
  JPEGENC_CBR = 1,         /**< CBR RC mode. */
  JPEGENC_VBR = 2,         /**< VBR RC mode. */
} JpegEncRcMode;

/** Specify parameters type to update or retrieve */
typedef enum {
  /** parameters for size of encoded picture (TBD) */
  JPEGENC_PARAM_SIZE = 0,
  /** parameters for rate control (TBD) */
  JPEGENC_PARAM_RC,
  /** parameters for quality */
  JPEGENC_PARAM_QUALITY,
  /** parameters for ROI Map (TBD) */
  JPEGENC_PRRAM_ROIMAP,
  /** number for parameter type */
  JPEGENC_PARAM_MAX
} JpegEncParamType;

/**@}*/

/*------------------------------------------------------------------------------
    3. Data types
------------------------------------------------------------------------------*/
/**
 * \defgroup api_info Helper Functions
 *
 * @{
 */

/** \brief Indicates API version information. */
typedef VceApiVersion JpegEncApiVersion;

/** \brief Indicates build information. */
typedef VceBuildInfo JpegEncBuild;

/**@}*/

/** \brief  Thumbnail information. */
typedef struct {
  JpegEncThumbFormat format; /**< \brief Thumbnail format.*/
  u16 width;                  /**< \brief Thumbnail width in pixels. */
  u16 height;                 /**< \brief Thumbnail height in pixels. */
  const void *data;          /**< \brief Thumbnail data. */
  u32 dataLength;            /**< \brief Data amount in bytes. */
} JpegEncThumb;

/** \brief  Configures RGB-to-YUV color space conversion. For how the following parameters
  * are used, see Section <tt> \ref ss_csc</tt>. */
typedef struct {
  /** \brief Pre-defined color conversion types. Besides the user-defined type,
   * some standard color conversion types are defined for setting coefficients quickly. */
  JpegEncColorConversionType type;
  u16 coeffA;     /**< \brief  User-defined color space conversion coefficient A. */
  u16 coeffB;     /**< \brief  User-defined color space conversion coefficient B. */
  u16 coeffC;     /**< \brief  User-defined color space conversion coefficient C. */
  u16 coeffE;     /**< \brief  User-defined color space conversion coefficient E. */
  u16 coeffF;     /**< \brief  User-defined color space conversion coefficient F. */
  u16 coeffG;     /**< \brief  User-defined color space conversion coefficient G. */
  u16 coeffH;     /**< \brief  User-defined color space conversion coefficient H. */
  u16 LumaOffset; /**< \brief  User-defined color space conversion parameter LumaOffset. */
} JpegEncColorConversion;

typedef enum {
  JPEG_UFBC_MODE_NONE = 0,
  JPEG_UFBC_MODE_AFBC_0 = 1,
  JPEG_UFBC_MODE_AFBC_1 = 2,
  JPEG_UFBC_MODE_DEC400 = 3,
  JPEG_UFBC_MODE_PVRIC = 4,
} jpeg_ufbcMode;

/** \brief Contains parameters when the core of UFBC is AFBC. */
typedef struct {
  /** \brief Whether to enable RGB-to-YUV conversion in UFBC.
   *  \n <tt>0</tt>: disable.
   *  \n <tt>1</tt>: enable. */
  u32 yuvTrans;
  /** \brief The superblock type of UFBC.
   *  \n <tt>0</tt>: 32x8.
   *  \n <tt>1</tt>: 16x16. */
  u32 blockType;
  /** \brief Whether to enable block split mode in UFBC.
   *  \n <tt>0</tt>: Block split mode off.
   *  \n <tt>1</tt>: Block split mode on. */
  u32 blockSplit;
} jpeg_ufbc_afbc_param;

/** \brief Contains parameters when the core of UFBC is PVRIC. */
typedef struct {
  /** \brief Surface tile mode.
   *  \n <tt>0</tt>: 8x8.
   *  \n <tt>1</tt>: 16x4.
   *  \n <tt>2</tt>: 32x2. */
  u32 blockType;
  /** \brief constant color value. */
  u32 consColorVal[4];
} jpeg_ufbc_pvric_param;

/** \brief Contains the UFBC parameters. */
typedef struct {
  /** \brief Whether to enable block split mode in UFBC.
   *  \n <tt>JPEG_UFBC_MODE_NONE</tt>: UFBC disable.
   *  \n <tt>JPEG_UFBC_MODE_AFBC_0</tt>: Use the core of AFBC version 0.(only support 32x8 superblock).
   *  \n <tt>JPEG_UFBC_MODE_AFBC_1</tt>: Use the core of AFBC version 1.(Support 32x8 and 16x16 superblock).
   *  \n <tt>JPEG_UFBC_MODE_DEC400</tt>: Use the core of Dec400. */
  jpeg_ufbcMode mode;
  union {
    jpeg_ufbc_afbc_param afbc;
    jpeg_ufbc_pvric_param pvric;
  } param;
} jpeg_ufbc_param;

/** \brief  Indicates encoder configuration. */
typedef struct {
  /** \brief  The number of pixels per line in an input picture. */
  u32 inputWidth;
  /** \brief  The number of lines in an input picture. */
  u32 inputHeight;
  /** \brief  The horizontal offset of top-left encoded picture relative to
   * the top-left corner of an input picture. */
  u32 xOffset;
  /** \brief  The vertical offset of top-left encoded picture relative to the top-left corner of an input picture. */
  u32 yOffset;
  /** \brief  The width of an encoded picture. */
  u32 codingWidth;
  /** \brief  The height of an encoded picture. */
  u32 codingHeight;
  /** \brief  The restart interval in MCU rows. */
  u32 restartInterval;

  /** \brief the quality factor from 1 to 100
   * when quality factor is -1, use qLevel */
  i32 quality;

  /** \brief  The quantization level.\n
   * Levels 0 through 9 use the predefined quantization table. \n
   * Level 10 uses the external quantization table specified in <tt>qTableLuma</tt> and <tt>qTableChroma</tt>. */
  u32 qLevel;
  /** \brief Quantization table for luminance, which is used when the quantization level is 10. */
  const u8 *qTableLuma;
  /** \brief Quantization table for chrominance, which is used when the quantization level is 10. */
  const u8 *qTableChroma;

  /** \brief Two 8x8 filters defined for luma and chroma non-ROI regions. */
  u8 filter[128];
  u32 enableRoimap; /**< \brief  Status of the ROI map feature. */
  u32 nonRoiLevel;  /**< \brief  Non-ROI filter level (0 to 9). */

  JpegEncFrameType frameType; /**< \brief  Input frame in YUV or RGB format. */
  /** \brief  Whether to enable RGB-to-YUV conversion. \n <tt>0</tt>: Disable. \n <tt>1</tt>: Enable. */
  JpegEncColorConversion colorConversion;
  /** \brief  Picture rotation mode. */
  JpegEncPictureRotation rotation;
  /** \brief  Whether to enable mirror. \n <tt>0</tt>: Disable. \n <tt>1</tt>: Enable. */
  u32 mirror;
  /** \brief  Encoding type, which can be either whole frame or restart interval. */
  JpegEncCodingType codingType;

  /** \brief  Encoding mode, which can be YUV420, monochrome, or YUV422 coding (pre-processing only supports one special YUV422 format). */
  JpegEncCodingMode codingMode;
  /** \brief  Unit for X and Y density in APP0. */
  JpegEncAppUnitsType unitsType;
  /** \brief  Specifies picture scan types for pre-processing. */
  JpegEncPictureScanType scanType;

  /** \brief  Table marker type. */
  JpegEncTableMarkerType markerType;
  u32 xDensity;   /**< \brief  The horizontal pixel density. */
  u32 yDensity;   /**< \brief  The vertical pixel density. */
  u32 comLength;  /**< \brief  The comment header length. */
  const u8 *pCom; /**< \brief  The comment header pointer. */

  /* low latency */
  u32 inputLineBufEn;         /**< \brief  Whether to enable input picture control signals. \n <tt>0</tt>: Disable. \n <tt>1</tt>: Enable.*/
  u32 inputLineBufLoopBackEn; /**< \brief  Whether to enable input buffer loopback.  \n <tt>0</tt>: Disable. \n <tt>1</tt>: Enable. */
  u32 inputLineBufDepth;      /**< \brief  Input buffer depth in MCU rows. */
  u32 inputLineBufHwModeEn;   /**< \brief  Whether to enable hardware handshake.  \n <tt>0</tt>: Disable. \n <tt>1</tt>: Enable. */
  u32 amountPerLoopBack; /**< \brief  Synchronous handshake amount for every loopback. */

  /** \brief  Callback function. */
  EncInputLineBufCallBackFunc inputLineBufCbFunc;
  void *inputLineBufCbData; /**< \brief  Callback function data. */
  /** \brief  The hash type for verifying stream correctness.
   * \n <tt>0</tt>: Disabled. \n <tt>1</tt>: CRC32 \n <tt>2</tt>: Checksum. */
  u32 hashType;

  /** \brief Whether the constant chroma control is enabled. \n If enabled, chroma is encoded as constant values.
   * \n <tt>0</tt>: Disabled. \n <tt>1</tt>: Enabled. */
  i32 constChromaEn;
  /** \brief The constant value for the U component, when constant chroma control is enabled. */
  u32 constCb;
  /** \brief The constant value for the V component, when constant chroma control is enabled. */
  u32 constCr;

  /** \brief Whether to enable lossless mode. \n If enabled, JPEG lossless mode (SOF3) is used.
   * \n <tt>0</tt>: Disable. \n <tt>1</tt>: Enable. */
  u32 losslessEn;
  /** \brief The predictor mode used for JPEG lossless processing.
   * The value of the nominator of frame rate ranges from 0 to 7. */
  u32 predictMode;
  /** \brief A point transform value used for lossless processing. */
  u32 ptransValue;

  /* Rate control*/
  u32 targetBitPerSecond; /**< \brief  Target bit per second. */

  /* Rate control for MJPEG purpose */
  /** \brief  The numerator of the frame rate. Value range [1, 1048575]. */
  u32 frameRateNum;
   /** \brief  The denominator of the frame rate. Value range [1, frameRateNum].
    * \n The frame rate is the result of frameRateNum divided by frameRateDenom in frames per second. */
  u32 frameRateDenom;
  /** \brief The minimum QP allowed during rate control for motion JPEG. */
  u32 qpmin;
  /** \brief The maximum QP allowed during rate control for motion JPEG. */
  u32 qpmax;
  /** \brief  Fixed QP without rate control. */
  i32 fixedQP;
  /** \brief Rate control mode. */
  JpegEncRcMode rcMode;
  /** \brief Obsolete. */
  i32 picQpDeltaMin;
  /** \brief Obsolete. */
  i32 picQpDeltaMax;
  /** \brief Stride used for input picture width. */
  u32 exp_of_input_alignment;

  /** \brief Slice node index. */
  u32 slice_idx;

  /* stream multi-segment */

  /** \brief Stream multi-segment control mode.
   * \n <tt>0</tt>: Segment disabled.
   * \n <tt>1</tt>: (Reserved) Multi-segment with loopback and no synchronous control.
   * \n <tt>2</tt>: (Reserved) Multi-segment with loopback and software synchronous control.
   * \n <tt>3</tt>: Multi-segment without loopback and no synchronous control. */
  u32 streamMultiSegmentMode;
  /** \brief The total number of stream multi-segment buffers. \n
   * The number must be more than one. \n
   * When loopback is enabled, streams should be written from the start address after the last segment is filled. */
  u32 streamMultiSegmentAmount;
  /** \brief Stream segment buffer size. \n
   * Callback is triggered when one segment is filled. */
  u32 streamMultiSegmentSize;
  /** \brief Callback function is triggered when one stream segment is filled. */
  EncStreamMultiSegCallBackFunc streamMultiSegCbFunc;
  /** \brief Callback data context for stream multi-segment callback function. */
  void *streamMultiSegCbData;

  /** \brief  The maximum AXI burst length. */
  u32 burstMaxLength;
  /** \brief  AXI alignment control.
   * \n bit [31:28] <tt>AXI_burst_align_wr_common</tt>.
   * \n bit [27:24] <tt>AXI_burst_align_wr_stream</tt>.
   * \n bit [23:20] <tt>AXI_burst_align_wr_chroma_ref</tt>.
   * \n bit [19:16] <tt>AXI_burst_align_wr_luma_ref</tt>.
   * \n bit [15:12] <tt>AXI_burst_align_rd_common</tt>.
   * \n bit [11:8] <tt>AXI_burst_align_rd_prp</tt>.
   * \n bit [7:4] <tt>AXI_burst_align_rd_ch_ref_prefetch</tt>.
   * \n bit [3:0] <tt>AXI_burst_align_rd_lu_ref_prefetch</tt>. */
  u32 AXIAlignment;

  /** \brief Interrupt request type mask.
   * \n swreg1 bit 8 <tt>irq_type_sw_reset_mask</tt>.
   * \n swreg1 bit 7 <tt>irq_type_fuse_error_mask</tt>.
   * \n swreg1 bit 6 <tt>irq_type_buffer_full_mask</tt>.
   * \n swreg1 bit 5 <tt>irq_type_bus_error_mask</tt>.
   * \n swreg1 bit 4 <tt>irq_type_timeout_mask</tt>.
   * \n swreg1 bit 3 <tt>irq_type_strm_segment_mask</tt>.
   * \n swreg1 bit 2 <tt>irq_type_line_buffer_mask</tt>.
   * \n swreg1 bit 1 <tt>irq_type_slice_rdy_mask</tt>.
   * \n swreg1 bit 0 <tt>irq_type_frame_rdy_mask</tt>. */
  u32 irqTypeMask;

  /* overlay controls */
  /** \brief  The number of OSD input frames recorded to support the roll back feature. */
  u32 olFrameNum[MAX_OVERLAY_NUM];
  /** \brief Whether the control of each OSD area is enabled.
   * \n <tt>0</tt>: Disabled.
   * \n <tt>1</tt>: Enabled. */
  u32 olEnable[MAX_OVERLAY_NUM];
  /** \brief The input formats of each OSD area.
    *\n <tt>0</tt>: ARGB8888.
    *\n <tt>1</tt>: NV12.
    *\n <tt>2</tt>: Bitmap. */
  u32 olFormat[MAX_OVERLAY_NUM];
  /** \brief The global alpha value of each OSD area, not used for ARGB8888. */
  u32 olAlpha[MAX_OVERLAY_NUM];
  /** \brief Input source width of an OSD area. */
  u32 olWidth[MAX_OVERLAY_NUM];
  /** \brief The width of each OSD area after cropping. */
  u32 olCropWidth[MAX_OVERLAY_NUM];
  /** \brief The input source height of each OSD area. */
  u32 olHeight[MAX_OVERLAY_NUM];
  /** \brief The height of an OSD area after cropping. */
  u32 olCropHeight[MAX_OVERLAY_NUM];
  /** \brief The top left column offset of an OSD area. */
  u32 olXoffset[MAX_OVERLAY_NUM];
  /** \brief The horizontal offset X, which is the left edge of the cropping region. */
  u32 olCropXoffset[MAX_OVERLAY_NUM];
  /** \brief Top left row offset of an OSD area. */
  u32 olYoffset[MAX_OVERLAY_NUM];
  /** \brief The vertical offest Y, which is the top edge of the cropping region. */
  u32 olCropYoffset[MAX_OVERLAY_NUM];
  /** \brief The input luma stride which is stored for an OSD area. */
  u32 olYStride[MAX_OVERLAY_NUM];
  /** \brief The input chroma stride which is stored for an OSD area. */
  u32 olUVStride[MAX_OVERLAY_NUM];
  /** \brief The global luma Y value for bitmap format. */
  u32 olBitmapY[MAX_OVERLAY_NUM];
  /** \brief The global chroma Cb value for bitmap format. */
  u32 olBitmapU[MAX_OVERLAY_NUM];
  /** \brief The global chroma Cr value for bitmap format. */
  u32 olBitmapV[MAX_OVERLAY_NUM];
  /** \brief Whether the input is in super tile format. (For ARGB8888 format only)
    *\n <tt>0</tt>: Not in super tile format.
    *\n <tt>1</tt>: X-marjor super tile format.
    *\n <tt>2</tt>: Y-major super tile format. */
  u32 olSuperTile[MAX_OVERLAY_NUM];
  /** \brief (Reserved) The width of an OSD area after upscaling. */
  u32 olScaleWidth[MAX_OVERLAY_NUM];
  /** \brief (Reserved) The height of an OSD area after upscaling. */
  u32 olScaleHeight[MAX_OVERLAY_NUM];
  /** \brief The size of the compression table buffer used by DEC400. */
  u32 osdDec400TableSize[MAX_OVERLAY_NUM][3];
  FILE *osdDec400TableFile[MAX_OVERLAY_NUM];

  /* Mosaic region control */
  /** \brief Whether the Mosaic region is enabled. (Not support Monochrome encoding if enable)
   * \n <tt>0</tt>: Disabled.
   * \n <tt>1</tt>: Enabled. */
  u32 mosEnable[MAX_MOSAIC_NUM];
  /** \brief The width of a mosaic region. */
  u32 mosWidth[MAX_MOSAIC_NUM];
  /** \brief The height of a mosaic region. */
  u32 mosHeight[MAX_MOSAIC_NUM];
  /** \brief The top left horizontal offset of a mosaic region. */
  u32 mosXoffset[MAX_MOSAIC_NUM];
  /** \brief The top left vertical offset of a mosaic region. */
  u32 mosYoffset[MAX_MOSAIC_NUM];
  u32 mosSizeIndex;

  /* OSD_MAP */
  u32 osdMapEnable;
  u32 osdMapStride;
  u32 osdMapBlockSize;
  u32 osdMapAlpha[MAX_OSDMAP_COLOR_NUM];
  u32 osdMapY[MAX_OSDMAP_COLOR_NUM];
  u32 osdMapU[MAX_OSDMAP_COLOR_NUM];
  u32 osdMapV[MAX_OSDMAP_COLOR_NUM];
  EWLLinearMem_t *osdMapMem;

  /* flexa sbi */

  /** \brief The FLEXA SBI ID is 0. */
  u32 sbi_id_0;
  /** \brief The FLEXA SBI ID is 1. */
  u32 sbi_id_1;
  /** \brief The FLEXA SBI ID is 2. */
  u32 sbi_id_2;
  /** \brief The FLEXA SBI segment unit height. */
  u32 segmentUnitHeight;

  /** \brief Whether powering down the internal SRAM automatically is enabled.
   * \n <tt>0</tt>: Enabled.
   * \n <tt>1</tt>: (Default) Disabled. */
  u32 sramPowerdownDisable;
  u32 sramPowerdownMode;
  u32 sramPowerdownTimerDiv32;
  /** \brief The debug option for dumpping register. */
  u32 dumpRegister;

/** \brief Contains the UFBC parameters. */
  jpeg_ufbc_param ufbcParam;

  /** \brief Whether security mode for encoding is enabled.
   * \n <tt>0</tt>: Disabled.
   * \n <tt>1</tt>: Enabled.*/
  u32 secure_mode;

	/** \brief Whether polling slice information mode of input low latency is enabled.
   * \n <tt>0</tt>: Disabled.
   * \n <tt>1</tt>: Enabled. */
  u32 sliceinfoEn;
  /** \brief the priority of current instance */
  u32 priority;

  /** \brief the core bit mask of current instance
   * \n <tt>0x0</tt>: not specify, anycore.
   * \n <tt>0x1</tt>: sepcfiy core0.
   * \n <tt>0x2</tt>: sepcfiy core1.*/
  u32 core_mask;

  /** \brief the device name of enc driver.
   *  \n default is "vsi_vcx" */
  char *enc_dev;

  /** \brief the device name of memalloc driver
   *  \n default is "memalloc" */
  char *mem_dev;
  /** \brief Whether to use vcmd.
   *  \n This field is valid only for cmodel. */
  u32 useVcmd;
  /** \brief lowlatency handshake auto gating disable
   *  \n <tt>0</tt>: enable.
   *  \n <tt>1</tt>: disable. */
  u32 lowlatGatingDisable;
} JpegEncCfg;

/** \brief  Configures encoding input information. */
typedef struct {
  /** \brief  Whether to create a frame header.
   * \n <tt>0</tt>: No.
   * \n <tt>1</tt>: Yes. */
  u32 frameHeader;

  /** \brief The bus address for input luminance (Y) picture.
   * \n Planar format: luminance component.
   * \n Semi-planar format: luminance component.
   * \n Interleaved format: whole picture. */
  ptr_t busLum;
  /** \brief The bus address for input chrominance (U).
   * \n Planar format: U component.
   * \n Semi-planar format: both chrominance.
   * \n Interleaved format: not used. */
  ptr_t busCb;
  /** \brief The bus address for input chrominance (V).
   * \n Planar format: V component.
   * \n Semi-planar format: not used.
   * \n Interleaved format: not used. */
  ptr_t busCr;

  /** \brief The bitmap buffer for ROI definition. Each bit defines one MCU. */
  ptr_t busRoiMap;
  /** \brief Quantization table filter, when 0 is set
   * in the corresponding bit of the ROI map buffer. */
  u8 *filter;
  /** \brief Virtual address for input luminance   (Y). */
  const u8 *pLum;
  /** \brief Virtual address for input chrominance (U). */
  const u8 *pCb;
  /** \brief Virtual address for input chrominance (V). */
  const u8 *pCr;

  /* DEC400 */

  /** \brief  The bus address of DEC400 compression table for luminance input (Y). */
  ptr_t dec400TableBusLum;
  /** \brief  The bus address of DEC400 compression table for chrominance input (U). */
  ptr_t dec400TableBusCb;
  /** \brief  The bus address of DEC400 compression table for chrominance input (V). */
  ptr_t dec400TableBusCr;
  /** \brief  The virtual address of DEC400 compression table for luminance input (Y). */
  const u8 *dec400TablepLum;
  /** \brief  The virtual address of DEC400 compression table for chrominance input (U). */
  const u8 *dec400TablepCb;
  /** \brief  The virtual address of DEC400 compression table for chrominance input (V). */
  const u8 *dec400TablepCr;
  /** \brief [0,7] Whether to enable DEC400.
   *  \n <tt>0</tt>: global-bypass or indicate dec400 doesn't exit.
   *  \n <tt>1</tt>: stream-bypass.
   *  \n <tt>2</tt>: enable. */
  /** \brief [8,15] DEC400 tileSize.
   *  \n <tt>0</tt>: default.
   *  \n <tt>1</tt>: 128byte.
   *  \n <tt>2</tt>: 512byte.
   *  \n <tt>3</tt>: 256byte. */
  /** \brief [16,23] DEC400 tileMode.
   *  \n <tt>0</tt>: default.
   *  \n <tt>1</tt>: TILE_8x8_x.
   *  \n <tt>2</tt>: TILE_8x8_y.
   *  \n <tt>3</tt>: TILE_16x4.
   *  \n <tt>4</tt>: TILE_8x4.
   *  \n <tt>5</tt>: TILE_4x8.
   *  \n <tt>6</tt>: RASTER_16x4.
   *  \n <tt>7</tt>: TILE_64x4.
   *  \n <tt>8</tt>: TILE_32x4.
   *  \n <tt>9</tt>: RASTER_256x1.
   *  \n <tt>10</tt>: RASTER_128x1.
   *  \n <tt>11</tt>: RASTER_64x1.
   *  \n <tt>12</tt>: TILE_16x8.
   *  \n <tt>13</tt>: RASTER_32x4.
   *  \n <tt>14</tt>: RASTER_32x1.
   *  \n <tt>15</tt>: RASTER_16x1.
   *  \n <tt>16</tt>: TILE_8x4_s.
   *  \n <tt>17</tt>: TILE_16x4_s.
   *  \n <tt>18</tt>: TILE_32x4_s.
   *  \n <tt>19</tt>: TILE_32x8. */
  /** \brief [25,27] DEC400 RGB format.
   *  \n <tt>0</tt>: default.
   *  \n <tt>1</tt>: RGB8.
   *  \n <tt>2</tt>: RGB10.
   *  \n <tt>3</tt>: RGB4.
   *  \n <tt>4</tt>: RGB1555.
   *  \n <tt>5</tt>: RGB565.*/
  /** \brief [28,28] DEC400 RGB format X or A.
   *  \n <tt>0</tt>: ARGB.
   *  \n <tt>1</tt>: XRGB. */
  /** \brief [29,31] DEC400 data alignment.
   *  \n <tt>0</tt>: default.
   *  \n <tt>1</tt>: 32byte.
   *  \n <tt>2</tt>: 64byte.
   *  \n <tt>3</tt>: 1byte.
   *  \n <tt>4</tt>: 16byte. */
  u32 dec400Enable;
  /** \brief Bus adress of sliceinfo data */
  ptr_t sliceinfoBus;
  /* AXIFE */

  /** \brief The working mode of AXI_FE.
   * \n <tt>0</tt>: Disabled.  \n <tt>1</tt>: Normal mode.
   * \n <tt>2</tt>: Bypass. \n <tt>3</tt>: Security mode. */
  u32 axiFEEnable;

  /* output buffers */
  /** \brief  The virtual address of the output stream buffer. */
  u8 *pOutBuf[MAX_STRM_BUF_NUM];
  /** \brief  The bus address of the output stream buffer. */
  ptr_t busOutBuf[MAX_STRM_BUF_NUM];
  /** \brief  The output buffer size in bytes. */
  u32 outBufSize[MAX_STRM_BUF_NUM];

  /** \brief  The number of MCU rows in the input MCU row buffer. */
  u32 lineBufWrCnt;
  /** \brief  The number of segments where input data is stored. */
  u32 initSegNum;

  /* overlay */
  /** \brief Whether to enable one overlay region.
   *  \n <tt>0</tt>: Disable.
   *  \n <tt>1</tt>: Enable. */
  u32 overlayEnable[MAX_OVERLAY_NUM];
  /** \brief The bus address of the luma component buffer of an overlay picture. */
  ptr_t busOlLum[MAX_OVERLAY_NUM];
  /** \brief The bus address of the Cb component buffer of an overlay picture. */
  ptr_t busOlCb[MAX_OVERLAY_NUM];
  /** \brief The bus address of the Cr component buffer of an overlay picture. */
  ptr_t busOlCr[MAX_OVERLAY_NUM];
  /** \brief Whether the overlay picture of region 0 is compressed by DEC400.
   * \n <tt>0</tt>: No.
   * \n <tt>1</tt>: Bypass.
   * \n <tt>2</tt>: Yes. */
  u32 osdDec400Enable[MAX_OVERLAY_NUM];
  /** \brief The bus address of the DEC400 compression table when the overlay picture of region 0 is compressed by DEC400. */
  ptr_t osdDec400TableBase[MAX_OVERLAY_NUM][3];
  /** \brief (For internal use only) The number of pictures counted. */
  u32 picCnt;
  /** \brief OSDMap enable */
  u32 osdMapEnable;
  /** \brief OSD MAP buffer base address*/
  ptr_t osdMapInputAddr;
  /** \brief Enable the fast clear funtion of dec400.*/
  u32 fcEnable[3];
  /** \brief The clear color in 16 bpp or 32 bpp for YUV channel.*/
  u32 clearColorLow[3];
  /** \brief Whether to process dec400 tile status header buffer.*/
  u32 dec400TSHeaderEnable;
} JpegEncIn;

/** \brief  Indicates output information. */
typedef struct {
  /** \brief Encoded JFIF size in bytes. */
  u32 jfifSize;
  /** \brief  Unused bytes in buf0 tail*/
  u32 invalidBytesInBuf0Tail;
  /** \brief JPEG header size in bytes */
  u32 headerSize;
} JpegEncOut;

/** \brief Indicates the JPEG rate control parameters. */
typedef struct {
  /** \brief Whether to enable bit rate control by adjusting quantization parameters. Value range [0,1].
   * \n <tt>0</tt>: Disable. \n <tt>1</tt>: Enable. */
  u32 pictureRc;
  /** \brief QP for the next encoded picture when rate control is enabled. Value range [-1, 51].
   * \n The value <tt>-1</tt> indicates rate control calculates the initial QP for the first picture.
   * \n Other values indicate this QP is used as the initial QP for the first picture and rate control calculates the QP for the following pictures. */
  i32 qpHdr;
  u32 qpMin; /**< \brief   Reserved. */
  u32 qpMax; /**< \brief   Reserved. */
  /** \brief  Target bit rate in the unit of bits per second.
   * It is mandatory when RC is enabled. Value range [10000, 60000000]. */
  u32 bitPerSecond;
  /** \brief (Reserved) Whether to enable HRD. \n <tt>0</tt>: Disable. \n <tt>1</tt>: Enable. */
  u32 hrd;
  /** \brief Bit rate control window. Value range [1, 300].
   *  \n The target bit rate is recommended in input frames. */
  u32 bitrateWindow;
  /** \brief Fixed QP value for all intra pictures. Value range [0, 51].
   * \n The value 0 indicates rate control calculates intra QP. */
  u32 fixedIntraQp;
  /** \brief Tolerance of the maximum moving bit rate, which is the maximum limit of the instantaneous bit rate. */
  i32 tolMovingBitRate;
  /** \brief Reserved. */
  i32 monitorFrames;
  /** \brief The minimum picture QP delta. It is used to smooth quality change between pictures. */
  i32 picQpDeltaMin;
  /** \brief The maximum picture QP delta. It is used to smooth quality change between pictures. */
  i32 picQpDeltaMax;
  /** \brief Frame rate. */
  u32 frameRateNum;
  /** \brief The maximum frame rate is the result of <tt>frameRateNum</tt> divided by <tt>frameRateDenom</tt> in frames per second.
   * The actual frame rate is defined by time increment of encoded pictures.*/
  u32 frameRateDenom;
} JpegEncRateCtrl;

/** \brief Parameters to set quality of encoded picture */
typedef struct {
  /** valid quality factor is from 1 to 100. when factor is -1, other method
   * will be used to adjust the quantization table. */
  i32 factor;
} JpegEncQuality;

/*------------------------------------------------------------------------------
    4. Function prototypes
------------------------------------------------------------------------------*/

/**
 * \addtogroup jpegenc_api JPEG Encoder API
 *
 * @{
 */

/**
 * Initializes the encoder and returns an instance.
 * The configuration contains stream parameters that cannot be changed during encoding.
 *
 * \brief Creates and initializes encoder instance.
 *
 * \param [in] config A pointer to the <tt>JpegEncCfg</tt> structure that contains initial configuration
 *             parameters of the encoder. These parameters cannot be changed during encoding.
 * \param [inout] instAddr A pointer to a space where the new instance pointer of the encoder is stored.
 * \param [in] ctx A pointer to the context which is initialized in application and may be used by EWL. For example,
 *             when the device is open before initialization, the ctx can be used to transfer this data.
 *             If this parameter is not used by the application, its value can be NULL.
 * \returns <tt> \ref JpegEncRet </tt>
 */
JpegEncRet JpegEncInit(const JpegEncCfg *pEncCfg, JpegEncInst *instAddr,
                       void *ctx);

/**
 * Releases an encoder instance.
 *
 * \param [in] inst Encoder instance
 */
JpegEncRet JpegEncRelease(JpegEncInst inst);

/**
 * Set parameters used for encoding.
 *
 * \brief Set parameters used for encoding.
 *
 * \param [in] inst Encoder instance
 * \param [in] type of parameters to set
 * \param [in] parameters for corresponding type.
 * \returns  <tt> \ref JpegEncRet </tt>
 */
JpegEncRet JpegEncSetParams(JpegEncInst inst, JpegEncParamType type,
                                  void *param);
/**
 * Get parameters used for encoding.
 *
 * \brief Get parameters used for encoding.
 *
 * \param [in] inst Encoder instance
 * \param [in] type of parameters to set
 * \param [out] parameters for corresponding type.
 * \returns  <tt> \ref JpegEncRet </tt>
 */
JpegEncRet JpegEncGetParams(JpegEncInst inst, JpegEncParamType type,
                                  void *param);

/**
 * Specifies the encoding configuration.
 * \param [in] inst Encoder instance.
 * \param [in] pEncCfg A pointer to the current encoding configuration.
 * \returns <tt> \ref JpegEncRet </tt>
 */
JpegEncRet JpegEncSetPictureSize(JpegEncInst inst, const JpegEncCfg *pEncCfg);

/**
 * Specifies the thumbnail of a JPEG picture.
 *
 * \param [in] inst Encoder instance.
 * \param [in] JpegThumb Thumbnail information.
 * \return <tt> \ref JpegEncRet </tt>
 */
JpegEncRet JpegEncSetThumbnail(JpegEncInst inst, const JpegEncThumb *JpegThumb);

/**
 * Generates JPEG JFIF output based on the configuration.
 *
 * \param [in] inst Encoder instance.
 * \param [in] pEncIn A pointer to the input and output buffer, as well as control information.
 * \param [out] pEncOut  A pointer to the encoding result.
 * \return <tt> \ref JpegEncRet </tt>
 */
JpegEncRet JpegEncEncode(JpegEncInst inst, const JpegEncIn *pEncIn,
                         JpegEncOut *pEncOut);

/*------------------------------------------------------------------------------
  Encoder API for special application
------------------------------------------------------------------------------*/

/** Generates software markers and enables the hardware to encode one frame or one interval.
 * \param [in] inst Encoder instance.
 * \param [in] pEncIn A pointer to input and output buffer, as well as control information.
 * \param [out] pEncOut A pointer to the encoding result.
 * \return <tt> \ref JpegEncRet </tt>
 */
JpegEncRet JpegEncEncodeRun(JpegEncInst inst, const JpegEncIn *pEncIn,
                            JpegEncOut *pEncOut);
/**
 * Waits for the completion of one encoding task.
 * \param [in] inst Encoder instance.
 * \param [out] pEncOut A pointer to the storage space for receiving the encoding result.
 * \return <tt> \ref JpegEncRet </tt>
 */
JpegEncRet JpegEncEncodeWait(JpegEncInst inst, JpegEncOut *pEncOut);
/** @} */

/**
 * \defgroup api_ull Low-Latency Control API
 *
 * @{
 */

/**
 * Obtains the number of the encoded input MCU rows of the current picture.
 *
 * \param [in] inst Encoder instance.
 * \return The number of encoded MCU rows.
 */
u32 JpegEncGetEncodedMbLines(JpegEncInst inst);

/**
 * Specifies the number of input buffer MCU rows of the current picture to be processed by the encoder.
 *
 * \param [in] inst Encoder instance.
 * \return <tt> \ref JpegEncRet </tt>
 */
JpegEncRet JpegEncSetInputMBLines(JpegEncInst inst, u32 lines);

/** @} */

/**
 * \defgroup api_rc MJPEG Bit Rate Control API
 *
 * @{
 */

/**
 * Obtains rate control configuration.
 *
 * \param [in] inst Encoder instance.
 * \param [in] pRateCtrl A pointer to the storage space for receiving the rate control configuration.
 * \return <tt> \ref JpegEncRet </tt>
 */
JpegEncRet JpegEncSetRateCtrl(JpegEncInst inst,
                              const JpegEncRateCtrl *pRateCtrl);
/**
 * Sets rate control configuration.
 *
 * \param [in] inst Encoder instance.
 * \param [out] pRateCtrl A pointer to the storage space for receiving the rate control configuration.
 * \return <tt> \ref JpegEncRet </tt>
 */
JpegEncRet JpegEncGetRateCtrl(JpegEncInst inst, JpegEncRateCtrl *pRateCtrl);

/** @} */

/**
 * \addtogroup api_info Helper API
 *
 * @{
 */

/**
 * Obtains function version information.
 *
 * \return Function version information. */
JpegEncApiVersion JpegEncGetApiVersion(void);

/**
 * Obtains build information about the specified core.
 *
 * \param [in] id Core ID.
 * \param [in] ctx Context used to initialize the instance.
 * \return Build information.
 */
JpegEncBuild JpegEncGetBuild(u32 id, const void *ctx);

/**
 * Specifies whether a core supports a specified feature.
 *
 * \param [in] feature Configuration of the core.
 * \param [in] cfg Required configuration.
 * \return <tt>1</tt>: Features indicated in cfg are supported.
 * \return <tt>0</tt>: Not supported.
 */
int JpegEncCoreHasFeatures(const EWLHwConfig_t *feature, EWLHwConfig_t *cfg);

/**
 * Obtains the bit depth of an input format.
 *
 * \param [in] type Picture format.
 * \return Bit depth (bits per pixel) of the specified format.
 */
u32 JpegEncGetBitsPerPixel(JpegEncFrameType type);

/**
 * Obtains the stride in bytes based on the specified alignment and format.
 *
 * \param [in] width Picture width in pixels.
 * \param [in] input_format Picture format.
 * \param [out] luma_stride A pointer to fill the required luma stride in bytes.
 * \param [out] chroma_stride A pointer to fill the required chroma stride in bytes.
 * \param [in] input_alignment User-specified alignment requirement in bytes.
 *     If there is no requirement on the alignment, this parameter can be set to zero.
 * \return Bytes of one pixel.
 */
u32 JpegEncGetAlignedStride(int width, i32 input_format, u32 *luma_stride,
                            u32 *chroma_stride, u32 input_alignment, u32 scan_type);
u32 JpegEncGetUfbcAlignment(u32 input_format, u32 blockType);
u32 JpegEncPreGetHwFormat(u32 input_format);



/*------------------------------------------------------------------------------
    Encoder API for set/get luma chroma size and QpHdr
------------------------------------------------------------------------------*/

/** Obtains the size information of the luma input buffer in an instance.
 *
 * \param [in] inst Encoder instance.
 * \param [out] lumSize A pointer to the storage space for receiving the size of the input luma buffer.
 * \param [out] dec400LumaTableSize A pointer to the storage space for receiving the DEC400 table size of the input luma buffer.
 */
JpegEncRet JpegGetLumaSize(JpegEncInst inst, u64 *lumaSize,
                           u64 *dec400LumaTableSize);

/** Sets the size of the luma input buffer in an instance.
 *
 * \param [in] inst Encoder instance.
 * \param [in] lumSize The size of the corresponding input luma buffer.
 * \param [out] dec400LumaTableSize The DEC400 table size of the corresponding input luma buffer.
 */
JpegEncRet JpegSetLumaSize(JpegEncInst inst, u64 lumaSize,
                           u64 dec400LumaTableSize);

/** Obtains the size of the chroma input buffer in an instance.
 *
 * \param [in] inst Encoder instance.
 * \param [out] chromaSize A pointer to the storage space for receiving the size of the corresponding input chroma buffer.
 * \param [out] dec400ChrTableSize A pointer to the storage space for receiving the DEC400 table size of the corresponding input chroma buffer.
 */
JpegEncRet JpegGetChromaSize(JpegEncInst inst, u64 *chromaSize,
                             u64 *dec400ChrTableSize);

/** Sets the size of the input buffer in an instance.
 *
 * \param [in] inst Encoder instance.
 * \param [in] chromaSize A pointer to the storage space for receiving the size of the corresponding input chroma buffer.
 * \param [in] dec400ChrTableSize A pointer to the storage space for receiving the DEC400 table size of the corresponding input chroma buffer.
 */
JpegEncRet JpegSetChromaSize(JpegEncInst inst, u64 chromaSize,
                             u64 dec400ChrTableSize);

/** Obtains the QP used for encoding the current frame. The QP identifies picture encoding quality.
 *
 * \param [in] inst Encoder instance.
 * \return <tt>0</tt> to <tt>51</tt>, with <tt>0</tt> indicating the best quality and <tt>51</tt> the poorest quality.
 */
int JpegGetQpHdr(JpegEncInst inst);

/*------------------------------------------------------------------------------
    8. Encoder API for get ewl
------------------------------------------------------------------------------*/

/**
 * Obtains the EWL instance, which is used to allocate linear buffers.
 *
 * \param [in] inst Encoder instance.
 * \return EWL instance internally initialized.
 */
const void *JpegEncGetEwl(JpegEncInst inst);

/**
 * Obtains OSD slice information.
 *
 * \param [in] inst Encoder instance
 * \param [in] pEncIn A pointer to the input and output buffer, as well as control information.
 * \param [in] restartInterval MCU rows to be encoded as one interval except for the last one.
 * \param [in] partialCoding Enabling status of partial encoding.
 * \param [in] slice Interval index of the current partial encoding.
 * \param [in] sliceRows MCU rows for the current interval.
 */
void JpegEncGetOverlaySlice(JpegEncInst inst, JpegEncIn *pEncIn,
                            i32 restartInterval, i32 partialCoding, i32 slice,
                            i32 sliceRows, u32 yOffset);
void JpegEncGetOSDMapSlice(JpegEncInst inst, JpegEncIn *pEncIn,
                           i32 restartInterval, i32 partialCoding, i32 slice,
                           u32 yOffset);

/**
 * Obtains encoding performance.
 *
 * \param [in] inst Encoder instance.
 * \return Cycles used to encode one frame or one interval.
 */
u32 JpegEncGetPerformance(JpegEncInst inst);

/**
 * Specifies whether JPEG SBI is supported.
 *
 * \param [in] inst Encoder instance.
 * \return <tt>1</tt>: Supported.
 * \return <tt>0</tt>: Not supported.
 */
u32 JpegGetSbiSupport(JpegEncInst inst);

/**@}*/

#ifdef __cplusplus
}
#endif

#endif
