/*------------------------------------------------------------------------------
--                                                                            --
--       This software is confidential and proprietary and may be used        --
--        only as expressly authorized by a licensing agreement from          --
--                                                                            --
--                            VeriSilicon Inc.                                --
--                                                                            --
--                   (C) COPYRIGHT 2015 VeriSilicon Inc                       --
--                            ALL RIGHTS RESERVED                             --
--                                                                            --
--                 The entire notice above must be reproduced                 --
--                  on all copies and should not be removed.                  --
--                                                                            --
------------------------------------------------------------------------------*/

/* Register interface based on the document version v1.5.3 */
    HWIF_VCMD_HW_ID,
    HWIF_VCMD_HW_VERSION,
    HWIF_VCMD_HW_BUILDDATE,
    HWIF_VCMD_EXT_ABN_INTR_SRC,
    HWIF_VCMD_EXT_NORM_INTR_SRC,
    HWIF_VCMD_EXE_CMDBUF_COUNT,
    HWIF_VCMD_CMD_EXE,
    HWIF_VCMD_CMD_EXE_MSB,
    HWIF_VCMD_AXI_TOTALARLEN,
    HWIF_VCMD_AXI_TOTALR,
    HWIF_VCMD_AXI_TOTALAR,
    HWIF_VCMD_AXI_TOTALRLAST,
    HWIF_VCMD_AXI_TOTALAWLEN,
    HWIF_VCMD_AXI_TOTALW,
    HWIF_VCMD_AXI_TOTALAW,
    HWIF_VCMD_AXI_TOTALWLAST,
    HWIF_VCMD_AXI_TOTALB,
    HWIF_VCMD_AXI_ARVALID,
    HWIF_VCMD_AXI_ARREADY,
    HWIF_VCMD_AXI_RVALID,
    HWIF_VCMD_AXI_RREADY,
    HWIF_VCMD_AXI_AWVALID,
    HWIF_VCMD_AXI_AWREADY,
    HWIF_VCMD_AXI_WVALID,
    HWIF_VCMD_AXI_WREADY,
    HWIF_VCMD_AXI_BVALID,
    HWIF_VCMD_AXI_BREADY,
    HWIF_VCMD_HW_APBARBITER,
    HWIF_VCMD_HW_INITMODE,
    HWIF_VCMD_CORE_STATE,
    HWIF_VCMD_INIT_MODE,
    HWIF_VCMD_WORK_STATE,
    HWIF_VCMD_ARB_CHECK_EN,
    HWIF_VCMD_INIT_ENABLE,
    HWIF_VCMD_AXI_CLK_GATE_DISABLE,
    HWIF_VCMD_MASTER_OUT_CLK_GATE_DISABLE,
    HWIF_VCMD_CORE_CLK_GATE_DISABLE,
    HWIF_VCMD_ABORT_MODE,
    HWIF_VCMD_RESET_CORE,
    HWIF_VCMD_RESET_ALL,
    HWIF_VCMD_START_TRIGGER,
    HWIF_VCMD_IRQ_ARBRST,
    HWIF_VCMD_IRQ_JMP,
    HWIF_VCMD_IRQ_ARBERR,
    HWIF_VCMD_IRQ_ABORT,
    HWIF_VCMD_IRQ_CMDERR,
    HWIF_VCMD_IRQ_TIMEOUT,
    HWIF_VCMD_IRQ_BUSERR,
    HWIF_VCMD_IRQ_ENDCMD,
    HWIF_VCMD_IRQ_ARBRST_EN,
    HWIF_VCMD_IRQ_JMP_EN,
    HWIF_VCMD_IRQ_ARBERR_EN,
    HWIF_VCMD_IRQ_ABORT_EN,
    HWIF_VCMD_IRQ_CMDERR_EN,
    HWIF_VCMD_IRQ_TIMEOUT_EN,
    HWIF_VCMD_IRQ_BUSERR_EN,
    HWIF_VCMD_IRQ_ENDCMD_EN,
    HWIF_VCMD_TIMEOUT_ENABLE,
    HWIF_VCMD_TIMEOUT_CYCLES,
    HWIF_VCMD_CMDBUF_EXE_ADDR,
    HWIF_VCMD_CMDBUF_EXE_ADDR_MSB,
    HWIF_VCMD_CMDBUF_EXE_LENGTH,
    HWIF_VCMD_CMD_SWAP,
    HWIF_VCMD_DATA_SWAP,
    HWIF_VCMD_MAX_BURST_LEN,
    HWIF_VCMD_AXI_ID_RD,
    HWIF_VCMD_AXI_ID_WR,
    HWIF_VCMD_RDY_CMDBUF_COUNT,
    HWIF_VCMD_EXT_ABN_INTR_GATE,
    HWIF_VCMD_EXT_NORM_INTR_GATE,
    HWIF_VCMD_CMDBUF_EXE_ID,
    HWIF_VCMD_SRAM_TIMING_CTRL,
    HWIF_VCMD_ARB_WEIGHT,
    HWIF_VCMD_ARB_BW_OVERFLOW,
    HWIF_VCMD_ARB_URGENT,
    HWIF_VCMD_ARB_ENABLE,
    HWIF_VCMD_ARB_TIME_WINDOW_EXP,
    HWIF_VCMD_ARB_WINER_ID,
    HWIF_VCMD_ARB_CUR_ID,
    HWIF_VCMD_ARB_GRP_INFO,
    HWIF_VCMD_ARB_STATE,
    HWIF_VCMD_ARB_RST,
    HWIF_VCMD_ARB_ACK,
    HWIF_VCMD_ARB_FE,
    HWIF_VCMD_ARB_REQ,
    HWIF_VCMD_ARB_SATISFACTION,
