/*------------------------------------------------------------------------------
--                                                                            --
--       This software is confidential and proprietary and may be used        --
--        only as expressly authorized by a licensing agreement from          --
--                                                                            --
--                            VeriSilicon Inc.                                --
--                                                                            --
--                   (C) COPYRIGHT 2015 VeriSilicon Inc                       --
--                            ALL RIGHTS RESERVED                             --
--                                                                            --
--                 The entire notice above must be reproduced                 --
--                  on all copies and should not be removed.                  --
--                                                                            --
------------------------------------------------------------------------------*/
{ /* 9.2.3 */
  .id = 0x0000201B,
  .id_mask = 0xFFFF,
  /* decoding formats related */
  .hevc_support = 1,
  .hevc_main10_support = 1,
  .hevc_422_intra_support = 0,
  .vp9_support = 1,
  .vp9_profile2_support = 1,
  /* G1_H264 - 0: H264 not supported; 1 - Baseline; 2 - Main; 3 - High */
  .h264_support = 0,
  .h264_adv_support = 1,
  .h264_high10_support = 1,
  .h264_422_intra_support = 0,
  .mpeg4_support = 0,
  .custom_mpeg4_support = 0,
  .mpeg2_support = 0,
  .sorenson_spark_support = 0,
  .vc1_support = 0,
  .jpeg_support = 1,
  .rv_support = 0,
  .vp8_support = 0,
  .webp_support = 0,
  .vp7_support = 0,
  .vp6_support = 0,
  .avs_support = 0,
  .avs_plus_support = 0,
  .avs2_support = 1,
  .avs2_main10_support = 1,
  .av1_support = 1,
  .vvc_support = 0,
  /* resolution related */
  .vvc_max_dec_pic_width = 4096,
  .vvc_max_dec_pic_height = 2160,
  .av1_max_dec_pic_width = 4096,
  .av1_max_dec_pic_height = 2160,
  .hevc_max_dec_pic_width = 4096,
  .hevc_max_dec_pic_height = 2160,
  .vp9_max_dec_pic_width = 4096,
  .vp9_max_dec_pic_height = 2160,
  .h264_max_dec_pic_width = 4096,
  .h264_max_dec_pic_height = 2160,
  .mpeg4_max_dec_pic_width = 1920,
  .mpeg4_max_dec_pic_height = 1088,
  .mpeg2_max_dec_pic_width = 1920,
  .mpeg2_max_dec_pic_height = 1088,
  .sspark_max_dec_pic_width = 1920,
  .sspark_max_dec_pic_height = 1088,
  .vc1_max_dec_pic_width = 4096,
  .vc1_max_dec_pic_height = 2160,
  .rv_max_dec_pic_width = 1920,
  .rv_max_dec_pic_height = 1088,
  .vp8_max_dec_pic_width = 4096,
  .vp8_max_dec_pic_height = 2160,
  .vp7_max_dec_pic_width = 1920,
  .vp7_max_dec_pic_height = 1088,
  .vp6_max_dec_pic_width = 1920,
  .vp6_max_dec_pic_height = 1088,
  .avs_max_dec_pic_width = 1920,
  .avs_max_dec_pic_height = 1088,
  .divx_max_dec_pic_width = 1920,
  .divx_max_dec_pic_height = 1088,
  .img_max_dec_width = 32768,
  .img_max_dec_height = 32768,
  /* Other features */
  .addr64_support = 1,
  .rfc_support = 1,
  .qp_dump_support = 0,
  /* decoding flow supported */
  .low_latency_mode_support = 1,
  .vp9_hw_prob_support = 1,
  .partial_decoding_support = 0,
  /* pp related features */
  .max_ppu_count = 2,
  .pp_standalone = 1,
  .pp_version = UNFIED_PP,
  .max_pp_out_pic_width = {4096,4096,0,0},
  .max_pp_out_pic_height = {2160,2160,0,0},
  /* down scaling is also supported when pp input size (i.e., cropping output) exceeds pp max output size */
  .dscale_support = {1,0,0,0},
  .uscale_support = {1,0,0,0},
  /*low_cost_scale: Bicubic/Bilinear/Nearest/Area */
  .low_cost_scale_support = {1,0,0,0},
  /*scale: Area*/
  .only_area_scale_alg_support = {0,0,0,0},
  /*crop_step_rshift: 0:support odd/even crop, 1:support even crop*/
  .crop_step_rshift = 0,
  /* output format supported */
  .fmt_tile_support = {0,0,0,0},
  .fmt_supertile_support = {1,0,0,0},
  .fmt_output_tile8x8_support = {1,0,0,0},
  .fmt_p010_support = 1,
  .fmt_rgb_support = {1,0,0,0},
  .pp_planar_support = {0,0,0,0},
  .pp_yuv420_101010_support = 1,
  .second_crop_support = 0,
  /*pp_comp: 1:FBC, 2:DEC400, 3:PVFBC */
  .pp_comp_support = {2,0,0,0},
  .pp_420to422_support = {0,0,0,0},
  .pp_tiled_stride_shift = 3,
  .pp_support_6x = 0,
  .pp_area_optimize = 1,
  .other_legal_HV_support = 0,
  .pp_rfd = 0,
  .pp_dec400d = 0,
  .pp_flip_rotation = 0,
  .pp_3dlut = {0,0,0,0},
  .pp_blending = {0,0,0,0},
  .jpeg_444_to_422_odd_width_support = 1,
  /* sub_system supported */
  .shaper_alignment = ALIGN_256B,
},
{ /* 9.2.1.2 */
  .id = 0x00001FF0,
  .id_mask = 0xFFFF,
  /* decoding formats related */
  .hevc_support = 1,
  .hevc_main10_support = 1,
  .hevc_422_intra_support = 0,
  .vp9_support = 1,
  .vp9_profile2_support = 1,
  /* G1_H264 - 0: H264 not supported; 1 - Baseline; 2 - Main; 3 - High */
  .h264_support = 3,
  .h264_adv_support = 1,
  .h264_high10_support = 1,
  .h264_422_intra_support = 0,
  .mpeg4_support = 2,
  .custom_mpeg4_support = 1,
  .mpeg2_support = 1,
  .sorenson_spark_support = 1,
  .vc1_support = 3,
  .jpeg_support = 1,
  .rv_support = 1,
  .vp8_support = 1,
  .webp_support = 1,
  .vp7_support = 1,
  .vp6_support = 1,
  .avs_support = 1,
  .avs_plus_support = 1,
  .avs2_support = 1,
  .avs2_main10_support = 1,
  .av1_support = 1,
  .vvc_support = 0,
  /* resolution related */
  .vvc_max_dec_pic_width = 8192,
  .vvc_max_dec_pic_height = 8192,
  .av1_max_dec_pic_width = 8192,
  .av1_max_dec_pic_height = 8192,
  .hevc_max_dec_pic_width = 8192,
  .hevc_max_dec_pic_height = 8192,
  .vp9_max_dec_pic_width = 8192,
  .vp9_max_dec_pic_height = 8192,
  .h264_max_dec_pic_width = 8192,
  .h264_max_dec_pic_height = 8192,
  .mpeg4_max_dec_pic_width = 1920,
  .mpeg4_max_dec_pic_height = 1088,
  .mpeg2_max_dec_pic_width = 1920,
  .mpeg2_max_dec_pic_height = 1088,
  .sspark_max_dec_pic_width = 1920,
  .sspark_max_dec_pic_height = 1088,
  .vc1_max_dec_pic_width = 4096,
  .vc1_max_dec_pic_height = 2176,
  .rv_max_dec_pic_width = 1920,
  .rv_max_dec_pic_height = 1088,
  .vp8_max_dec_pic_width = 4096,
  .vp8_max_dec_pic_height = 2176,
  .vp7_max_dec_pic_width = 1920,
  .vp7_max_dec_pic_height = 1088,
  .vp6_max_dec_pic_width = 1920,
  .vp6_max_dec_pic_height = 1088,
  .avs_max_dec_pic_width = 1920,
  .avs_max_dec_pic_height = 1088,
  .divx_max_dec_pic_width = 1920,
  .divx_max_dec_pic_height = 1088,
  .img_max_dec_width = 32768,
  .img_max_dec_height = 32768,
  /* Other features */
  .addr64_support = 1,
  .rfc_support = 1,
  .qp_dump_support = 0,
  /* decoding flow supported */
  .low_latency_mode_support = 1,
  .vp9_hw_prob_support = 1,
  .partial_decoding_support = 0,
  /* pp related features */
  .max_ppu_count = 2,
  .pp_standalone = 1,
  .pp_version = UNFIED_PP,
  .max_pp_out_pic_width = {8192,8192,0,0},
  .max_pp_out_pic_height = {8192,8192,0,0},
  /* down scaling is also supported when pp input size (i.e., cropping output) exceeds pp max output size */
  .dscale_support = {1,1,0,0},
  .uscale_support = {0,1,0,0},
  /*low_cost_scale: Bicubic/Bilinear/Nearest/Area */
  .low_cost_scale_support = {0,0,0,0},
  /*scale: Area*/
  .only_area_scale_alg_support = {0,0,0,0},
  /*crop_step_rshift: 0:support odd/even crop, 1:support even crop*/
  .crop_step_rshift = 1,
  /* output format supported */
  .fmt_tile_support = {0,1,0,0},
  .fmt_supertile_support = {1,0,0,0},
  .fmt_output_tile8x8_support = {0,0,0,0},
  .fmt_p010_support = 1,
  .fmt_rgb_support = {0,1,0,0},
  .pp_planar_support = {0,0,0,0},
  .pp_yuv420_101010_support = 0,
  .second_crop_support = 0,
  /*pp_comp: 1:FBC, 2:DEC400, 3:PVFBC */
  .pp_comp_support = {2,2,0,0},
  .pp_420to422_support = {0,1,0,0},
  .pp_tiled_stride_shift = 3,
  .pp_support_6x = 1,
  .pp_area_optimize = 1,
  .other_legal_HV_support = 0,
  .pp_half_scale_support = {0,0,0,0},
  .pp_rfd = 0,
  .pp_dec400d = 0,
  .pp_flip_rotation = 0,
  .pp_3dlut = {0,0,0,0},
  .pp_blending = {0,0,0,0},
  .jpeg_444_to_422_odd_width_support = 0,
  /* sub_system supported */
  .shaper_alignment = ALIGN_256B,
},

#if 0
{ /* full_feature */
  .id = 0x0000FFFF,
  .id_mask = 0xFFFFFFFF,
  /* decoding formats related */
  .hevc_support = 1,
  .hevc_main10_support = 1,
  .hevc_422_intra_support = 1,
  .vp9_support = 1,
  .vp9_profile2_support = 1,
  /* G1_H264 - 0: H264 not supported; 1 - Baseline; 2 - Main; 3 - High */
  .h264_support = 3,
  .h264_adv_support = 1,
  .h264_high10_support = 1,
  .h264_422_intra_support = 1,
  .mpeg4_support = 2,
  .custom_mpeg4_support = 1,
  .mpeg2_support = 1,
  .sorenson_spark_support = 1,
  .vc1_support = 3,
  .jpeg_support = 1,
  .rv_support = 1,
  .vp8_support = 1,
  .webp_support = 1,
  .vp7_support = 1,
  .vp6_support = 1,
  .avs_support = 2,
  .avs_plus_support = 1,
  .avs2_support = 1,
  .avs2_main10_support = 1,
  .av1_support = 1,
  .vvc_support = 1,
  /* resolution related */
  .vvc_max_dec_pic_width = 8192,
  .vvc_max_dec_pic_height = 8192,
  .av1_max_dec_pic_width = 8192,
  .av1_max_dec_pic_height = 8192,
  .hevc_max_dec_pic_width = 8192,
  .hevc_max_dec_pic_height = 8192,
  .vp9_max_dec_pic_width = 8192,
  .vp9_max_dec_pic_height = 8192,
  .h264_max_dec_pic_width = 8192,
  .h264_max_dec_pic_height = 8192,
  .mpeg4_max_dec_pic_width = 1920,
  .mpeg4_max_dec_pic_height = 1088,
  .mpeg2_max_dec_pic_width = 1920,
  .mpeg2_max_dec_pic_height = 1088,
  .sspark_max_dec_pic_width = 1920,
  .sspark_max_dec_pic_height = 1088,
  .vc1_max_dec_pic_width = 4096,
  .vc1_max_dec_pic_height = 4096,
  .rv_max_dec_pic_width = 1920,
  .rv_max_dec_pic_height = 1088,
  .vp8_max_dec_pic_width = 4096,
  .vp8_max_dec_pic_height = 4096,
  .vp7_max_dec_pic_width = 1920,
  .vp7_max_dec_pic_height = 1088,
  .vp6_max_dec_pic_width = 1920,
  .vp6_max_dec_pic_height = 1088,
  .avs_max_dec_pic_width = 1920,
  .avs_max_dec_pic_height = 1088,
  .divx_max_dec_pic_width = 1920,
  .divx_max_dec_pic_height = 1088,
  .img_max_dec_width = 32768,
  .img_max_dec_height = 32768,
  /* Other features */
  .addr64_support = 1,
  .rfc_support = 1,
  .qp_dump_support = 1,
  /* decoding flow supported */
  .low_latency_mode_support = 1,
  .vp9_hw_prob_support = 0,
  .partial_decoding_support = 1,
  /* pp related features */
  .max_ppu_count = 5,
  .pp_standalone = 1,
  .pp_version = UNFIED_PP,
  .max_pp_out_pic_width = {8192,8192,8192,8192,8192},
  .max_pp_out_pic_height = {8192,8192,8192,8192,8192},
  /* down scaling is also supported when pp input size (i.e., cropping output) exceeds pp max output size */
  .dscale_support = {1,1,1,1,1},
  .uscale_support = {1,1,1,1,1},
  .crop_step_rshift = 1,
  /*low_cost_scale: Bicubic/Bilinear/Nearest/Area */
  .low_cost_scale_support = {1,1,1,1},
  /*scale: Area*/
  .only_area_scale_alg_support = {0,0,0,0},
  /*crop_step_rshift: 0:support odd/even crop, 1:support even crop*/
  /* output format supported */
  .fmt_tile_support = {1,1,1,1,1},
  .fmt_supertile_support = {0,0,0,0},
  .fmt_output_tile8x8_support = {0,0,0,0},
  .fmt_p010_support = 1,
  .fmt_rgb_support = {1,1,1,1,1},
  .pp_planar_support = {1,1,1,1,1},
  .pp_yuv420_101010_support = 1,
  .second_crop_support = 1,
  /*pp_comp: 1:FBC, 2:DEC400, 3:PVFBC */
  .pp_comp_support = {2,0,0,0},
  .pp_420to422_support = {0,1,0,0},
  .pp_tiled_stride_shift = 3,
  .pp_support_6x = 1,
  .pp_area_optimize = 1,
  .other_legal_HV_support = 1,
  .pp_half_scale_support = {0,0,0,0},
  .pp_rfd = 0,
  .pp_dec400d = 0,
  .pp_flip_rotation = 0,
  .pp_3dlut = {0,0,0,0},
  .pp_blending = {0,0,0,0},
  .jpeg_444_to_422_odd_width_support = 0,
  /* sub_system supported */
  .shaper_alignment = ALIGN_256B,
},
#endif